#!/usr/bin/env python3

import socket
import argparse
import requests


def login(args: argparse.Namespace):
    if args.address is None:
        args.address = get_addr()
    url = f'http://202.113.18.106:801/eportal/?c=ACSetting&a=Login&loginMethod=1&protocol=http%3A&hostname=202.113.18.106&port=&iTermType=1&wlanuserip={args.address}&wlanacip=null&wlanacname=zx_&redirect=null&session=null&vlanid=0&mac=00-00-00-00-00-00&ip={args.address}&enAdvert=0&jsVersion=2.4.3&DDDDD={args.user}&upass={args.password}&R1=0&R2=0&R3=0&R6=0&para=00&0MKKey=123456&buttonClicked=&redirect_url=&err_flag=&username=&password=&user=&cmd=&Login='
    headers = {
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'Referer': f'http://202.113.18.106/a70.htm?wlanuserip={args.address}&wlanacip=null&wlanacname=zx_&vlanid=0&ip={args.address}&ssid=null&areaID=null&mac=00-00-00-00-00-00&switch_url=null&ap_mac=null&client_mac=null&wlan=null',
        'Accept-Language': 'zh-CN,zh;q=0.9'
    }
    requests.get(url, headers=headers, verify=False)
    try:
        requests.get('https://www.baidu.com/', timeout=3)
        print('Login successful')
    except:
        print('Login failed')


def logout(_):
    url = 'http://202.113.18.106:801/eportal/?c=ACSetting&a=Logout&loginMethod=1&runRadius=1&DDDDD=&protocol=http%3A&hostname=202.113.18.106&port=&iTermType=1&wlanuserip=null&wlanacip=null&wlanacname=null&redirect=null&session=null&vlanid=undefined&mac=00-00-00-00-00-00&ip=&queryACIP=0&jsVersion=2.4.3'
    requests.get(url, verify=False)
    try:
        requests.get('https://www.baidu.com/', timeout=3)
        print('Logout failed')
    except:
        print('Logout successful')


def get_addr() -> str:
    print('Address not specified, trying to get the address of the device')
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("202.113.18.106", 80))
    addr = s.getsockname()[0]
    s.close()
    print(f'Address of the device: {addr}')
    return addr


parser = argparse.ArgumentParser(description='A script to login/logout to/from the campus network')
subparsers = parser.add_subparsers(dest='command')

login_parser = subparsers.add_parser('login')
login_parser.add_argument('-a', '--address', required=False, type=str,
                          help='IP address of the device')
login_parser.add_argument('-u', '--user', required=True, type=str, help='Username of your campus network account')
login_parser.add_argument('-p', '--password', required=True, type=str, help='Password of your campus network account')
login_parser.set_defaults(func=login)

logout_parser = subparsers.add_parser('logout')
logout_parser.set_defaults(func=logout)

args = parser.parse_args()
args.func(args)
